### ISSUE TITLE
Papermilling Loop Issue

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/dunir-emissions#14]
To make paper, you need cellulose fiber from a tailor and a small paper machine from a mechanic

Both Tailor and Mechanics require advanced research, which now require paper.

A suggestion proposed earlier was to introduce an inefficient paper recipe to the carpentry table, but it appears that was never applied.

**Comment by Halfshot555** [comment]
Suggested Recipe

Station: Carpentry Bench
Output: 1 Paper
Input: 100 <natural fiber> (Base recipe is 40 fiber/paper)
Craft Time: 15 seconds (Base recipe is 6s)
Labor: 200 (Base is 140 labor for fiber & paper steps)     

Do we want this recipe at papermilling 0/1 or generic to all. I'm inclined for paper 0 so if someone knows the scroll they can make the shitty recipe.

**Comment by Pingu-Pox** [comment]
Fix made, waiting to apply.

**Comment by Halfshot555** [comment]
![image](https://github.com/Pingu-Pox/dunir-emissions/assets/97805739/8e987c53-2e0c-469d-be52-c8b4fbda76cc)
Alternative recipe is active.
