### ISSUE TITLE
Fertilizer leveling gap.

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/dunir-emissions#18]
The fertilizers have a leveling issue you gain access to 3 of them at level 1 but you cant make anything to advance the level until level 2

I propose dropping fiber filler to be crafted at level 1
![image](https://github.com/Pingu-Pox/dunir-emissions/assets/102630179/ddbd0a6d-4699-4849-a05d-6d9ffbc23305)

**Comment by Halfshot555** [comment]
Fertilizer level 1 gives access to 1 filler and 2 fertilizers (that take filler as ingredient). 
Level 2 then gives another 1 filler + 2 fertilizers.

Unless the wood pulp filler is not working, I don't see anything stopping the skill from leveling.

![image](https://github.com/Pingu-Pox/dunir-emissions/assets/97805739/09a32265-b204-4a28-bbb6-dc2041a26af2)

**Comment by Pingu-Pox** [comment]
@JohannesRamheart @Halfshot555 So is this not a bug then? Difficulty understanding what the problem is?

**Comment by Halfshot555** [comment]
I believe it was a misread of what level 1 gave; thinking that the first filler isn't until level 2. I showed that there is a filler to craft at level 1.

I believe it is not a bug.

**Comment by Pingu-Pox** [comment]
Will close after @JohannesRamheart can confirm it was user-error.

**Comment by JohannesRamheart** [comment]
Confirmed
