### ISSUE TITLE
Found a research paper modern that doesn't require paper

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/dunir-emissions#23]
While looking at requirements for the Advanced Upgrade Mod 1, saw that Geo Research Modern has 2 recipes:
The pottery version of the recipe correctly has the premium paper and glue requirements. 
The Glassworking version only require glass.

![image](https://github.com/Pingu-Pox/dunir-emissions/assets/97805739/0425635a-2d0a-49dc-a6b9-8d70c8e40a8d)

![image](https://github.com/Pingu-Pox/dunir-emissions/assets/97805739/aa898b20-8f10-4761-9c25-e912d8f0f5dc)

**Comment by Pingu-Pox** [comment]
Wtf that's weird ty, looking into the fix.

**Comment by Pingu-Pox** [comment]
Fix applied, testing during maintenance

**Comment by Pingu-Pox** [comment]
Resolved
