### ISSUE TITLE
Sun Cheese -> Cheese tag

### ISSUE THREAD

**Issue by JohannesRamheart** [Pingu-Pox/dunir-emissions#26]
Changing the recipes includes: changing Sun Cheese, to [Cheese tag]

Agouti Enchiladas Recipe
Fantastic Forest Pizza Recipe
Hearty Hometown Pizza Recipe
Loaded Taro Fries Recipe
Nachos Recipe
Pupusas Recipe
Sensuous Sea Pizza Recipe
Tasty Tropical Pizza Recipe

Tag recipes include:
Sun Cheese Recipe
Cheese Recipe

Food Overhual

Tag code before:

    [RequiresSkill(typeof(FarmingSkill), 1)]
    [Ecopedia("Food", "Farming", subPageName: "Cheese Item")]
    public partial class CheeseRecipe : RecipeFamily
    
    Tag code after:
    [RequiresSkill(typeof(FarmingSkill), 1)]
    [Ecopedia("Food", "Farming", "Cheese", subPageName: "Cheese Item")]
    public partial class CheeseRecipe : RecipeFamily

**Comment by Pingu-Pox** [comment]
Change completed. Nachos excluded since no cs files are available for it (unless its named weird).
