### ISSUE TITLE
Disable DiscordLink integration for elections and voting

### ISSUE THREAD

**Issue by Pingu-Pox** [Pingu-Pox/dunir-emissions#4]
Prevent abuse

**Comment by Pingu-Pox** [comment]
Change made, awaiting testing with Kyandar.

**Comment by Halfshot555** [comment]
Notification that an election went live was posted to discord, but voting was disabled as expected. Having the notification is nice, but with multiple towns, may want to consider disabling even the notification to prevent too much spam to the channel.

![vote tested](https://github.com/Pingu-Pox/dunir-emissions/assets/97805739/6910209d-ed1b-4f4d-bfa4-8cab9cd08373)

**Comment by Pingu-Pox** [comment]
@Halfshot555 Try again, disabled election feed.

**Comment by Halfshot555** [comment]
Tested and confirmed that in game elections are not posted to discord.
